### ISSUE TITLE
Add cast of Tarantool object names to GraphQL names allowed characters (spaces, fields, indexes)

### ISSUE THREAD

**Issue by no1seman** [tarantool/graphqlapi#5]
All kind of Tarantool objects supports nearly all UTF-8 characters except a several ones, but according to GraphQL standart it supports only: [_A-Za-z][_0-9A-Za-z]* 

So, need to add transparent convertion from Tarantool names to GraphQL names and vice versus.

**Comment by filonenko-mikhail** [comment]
Sorry, no product plans. Gently closing.
